"""initial schema

Revision ID: 0114aa9f5ad3
Revises:
Create Date: 2026-09-06 03:34:11.644267
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0114aa9f5ad3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("image", "audio", "video", name="media_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("poster_storage_key", sa.String(length=1024), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "ready", "rejected", name="media_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms > 0", name=op.f("ck_media_assets_positive_duration")
        ),
        sa.CheckConstraint(
            "height IS NULL OR height > 0", name=op.f("ck_media_assets_positive_height")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_media_assets_positive_size")),
        sa.CheckConstraint(
            "width IS NULL OR width > 0", name=op.f("ck_media_assets_positive_width")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("checksum_sha256", name=op.f("uq_media_assets_checksum_sha256")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    op.create_index(op.f("ix_media_assets_status"), "media_assets", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("google_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("google_subject", name=op.f("uq_users_google_subject")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name_ar", sa.String(length=160), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=True),
        sa.Column("cover_media_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_media_id"],
            ["media_assets.id"],
            name=op.f("fk_categories_cover_media_id_media_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name_ar", name=op.f("uq_categories_name_ar")),
    )
    op.create_index(op.f("ix_categories_is_active"), "categories", ["is_active"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "setup",
                "active",
                "completed",
                "cancelled",
                "expired",
                name="match_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_team_no", sa.Integer(), nullable=False),
        sa.Column("timer_seconds", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("current_team_no IN (1, 2)", name=op.f("ck_matches_valid_current_team")),
        sa.CheckConstraint("timer_seconds BETWEEN 10 AND 300", name=op.f("ck_matches_valid_timer")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_matches_positive_version")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_matches_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index("ix_matches_owner_status", "matches", ["owner_id", "status"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "match_categories",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 6", name=op.f("ck_match_categories_valid_position")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_match_categories_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_categories_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_id", "category_id", name=op.f("pk_match_categories")),
        sa.UniqueConstraint("match_id", "category_id", name="uq_match_categories_category"),
        sa.UniqueConstraint("match_id", "position", name="uq_match_categories_position"),
    )
    op.create_table(
        "match_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence_no >= 1", name=op.f("ck_match_events_positive_sequence")),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_match_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_events_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_events")),
        sa.UniqueConstraint("match_id", "idempotency_key", name="uq_match_events_idempotency"),
        sa.UniqueConstraint("match_id", "sequence_no", name="uq_match_events_sequence"),
    )
    op.create_table(
        "match_teams",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("team_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.CheckConstraint("score >= 0", name=op.f("ck_match_teams_nonnegative_score")),
        sa.CheckConstraint("team_no IN (1, 2)", name=op.f("ck_match_teams_valid_team")),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_teams_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("match_id", "team_no", name=op.f("pk_match_teams")),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum("text", "image", "audio", "video", name="question_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("prompt_ar", sa.Text(), nullable=False),
        sa.Column("answer_ar", sa.Text(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("media_asset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "options_reveal_timing",
            sa.Enum("immediate", "after_media", name="options_reveal_timing", native_enum=False),
            nullable=False,
        ),
        sa.Column("max_plays", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "retired", name="question_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("points IN (200, 400, 600)", name=op.f("ck_questions_valid_points")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_questions_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_questions_media_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    op.create_index(
        "ix_questions_category_points_status",
        "questions",
        ["category_id", "points", "status"],
        unique=False,
    )
    op.create_table(
        "match_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("category_position", sa.Integer(), nullable=False),
        sa.Column("slot_position", sa.Integer(), nullable=False),
        sa.Column(
            "question_type_snapshot",
            sa.Enum(
                "text", "image", "audio", "video", name="match_question_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("prompt_snapshot", sa.Text(), nullable=False),
        sa.Column("answer_snapshot", sa.Text(), nullable=False),
        sa.Column("options_snapshot", sa.JSON(), nullable=False),
        sa.Column("media_asset_id_snapshot", sa.Uuid(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "available",
                "prepared",
                "open",
                "revealed",
                "scored",
                "replaced",
                name="match_question_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("max_plays", sa.Integer(), nullable=True),
        sa.Column("play_count", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("media_ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_by_team_no", sa.Integer(), nullable=True),
        sa.Column("awarded_points", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "answered_by_team_no IS NULL OR answered_by_team_no IN (1, 2)",
            name=op.f("ck_match_questions_valid_answered_team"),
        ),
        sa.CheckConstraint(
            "awarded_points >= 0", name=op.f("ck_match_questions_nonnegative_award")
        ),
        sa.CheckConstraint(
            "category_position BETWEEN 0 AND 6",
            name=op.f("ck_match_questions_valid_category_position"),
        ),
        sa.CheckConstraint(
            "max_plays IS NULL OR max_plays > 0", name=op.f("ck_match_questions_positive_max_plays")
        ),
        sa.CheckConstraint(
            "play_count >= 0", name=op.f("ck_match_questions_nonnegative_play_count")
        ),
        sa.CheckConstraint(
            "points IN (200, 400, 600)", name=op.f("ck_match_questions_valid_points")
        ),
        sa.CheckConstraint(
            "slot_position BETWEEN 0 AND 5", name=op.f("ck_match_questions_valid_slot_position")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_questions_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id_snapshot"],
            ["media_assets.id"],
            name=op.f("fk_match_questions_media_asset_id_snapshot_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_match_questions_question_id_questions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_questions")),
        sa.UniqueConstraint(
            "match_id", "category_position", "slot_position", name="uq_match_questions_slot"
        ),
        sa.UniqueConstraint("match_id", "question_id", name="uq_match_questions_question"),
    )
    op.create_index(
        "ix_match_questions_match_state", "match_questions", ["match_id", "state"], unique=False
    )
    op.create_table(
        "question_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("text_ar", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_question_options_nonnegative_sort_order")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_options_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_options")),
        sa.UniqueConstraint("question_id", "sort_order", name="uq_question_options_question_sort"),
    )
    op.create_index(
        op.f("ix_question_options_question_id"), "question_options", ["question_id"], unique=False
    )
    op.create_table(
        "user_question_usage",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("first_match_id", sa.Uuid(), nullable=False),
        sa.Column(
            "first_used_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_match_id"],
            ["matches.id"],
            name=op.f("fk_user_question_usage_first_match_id_matches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_user_question_usage_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_question_usage_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "question_id", name=op.f("pk_user_question_usage")),
    )
    op.create_table(
        "match_lifelines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("team_no", sa.Integer(), nullable=False),
        sa.Column(
            "lifeline_type",
            sa.Enum(
                "two_answers",
                "double_points",
                "block_opponent",
                name="lifeline_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum("available", "armed", "used", name="lifeline_state", native_enum=False),
            nullable=False,
        ),
        sa.Column("match_question_id", sa.Uuid(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("team_no IN (1, 2)", name=op.f("ck_match_lifelines_valid_team")),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name=op.f("fk_match_lifelines_match_id_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["match_question_id"],
            ["match_questions.id"],
            name=op.f("fk_match_lifelines_match_question_id_match_questions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_lifelines")),
        sa.UniqueConstraint(
            "match_id", "team_no", "lifeline_type", name="uq_match_lifelines_team_type"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_lifelines")
    op.drop_table("user_question_usage")
    op.drop_index(op.f("ix_question_options_question_id"), table_name="question_options")
    op.drop_table("question_options")
    op.drop_index("ix_match_questions_match_state", table_name="match_questions")
    op.drop_table("match_questions")
    op.drop_index("ix_questions_category_points_status", table_name="questions")
    op.drop_table("questions")
    op.drop_table("match_teams")
    op.drop_table("match_events")
    op.drop_table("match_categories")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_matches_owner_status", table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_categories_is_active"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_media_assets_status"), table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
