"""add choosing team to match questions

Revision ID: dad632bd6715
Revises: 0114aa9f5ad3
Create Date: 2026-09-06 03:44:59.386464
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dad632bd6715"
down_revision: str | Sequence[str] | None = "0114aa9f5ad3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_questions", sa.Column("choosing_team_no", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match_questions", "choosing_team_no")
    # ### end Alembic commands ###
